version: '3.8'

services:
  connector-api:
    build:
      context: ./connector-api
    image: cloudolife/col-rust-docker
    container_name: connector-api
    command: cargo run
    ports:
    - "4000:4000"
    restart: on-failure
    depends_on:
      - monitoring_db
    volumes:
      - "./connector-api:/usr/connector-api"
      - "./matchmaking-state:/usr/matchmaking-state"
    environment:
      - HOST_URL=0.0.0.0:4000
      - REDIS_URL=redis://monitoring_db:6379

  match-creator:
    build:
      context: ./match-creator
    image: cloudolife/col-rust-docker
    container_name: match-creator
    command: cargo run
    restart: on-failure
    depends_on:
      - monitoring_db
    volumes:
      - "./match-creator:/usr/match-creator"
      - "./matchmaking-state:/usr/matchmaking-state"
    environment:
      - REDIS_URL=redis://monitoring_db:6379

  games-agent:
    build:
      context: ./games-agent
    image: cloudolife/col-rust-docker
    container_name: games-agent
    command: cargo run
    restart: on-failure
    depends_on:
      - monitoring_db
    volumes:
      - "./games-agent:/usr/games-agent"
      - "./matchmaking-state:/usr/matchmaking-state"
    environment:
      - REDIS_URL=redis://monitoring_db:6379

  automate:
    build:
      context: ./automate
    image: python:3.11-slim 
    container_name: automate
    command: "python auto.py"
    restart: on-failure
    depends_on:
      - monitoring_db
    volumes:
      - "./automate:/usr/automate"
      - "./matchmaking-state/scripts:/usr/matchmaking-state/scripts"

  monitoring_db:
    image: redis:latest
    container_name: monitoring_db
    ports:
      - "6379:6379"
    volumes:
      - monitoring_data:/data
  

volumes:
  monitoring_data:

networks:
  redis_network:
    driver: bridge