version: "3.8"

services:
  connector-api:
    build:
      context: ./connector-api
    container_name: connector-api
    command: cargo run --release
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - redis
    environment:
      - HOST_URL=0.0.0.0:4000
      - REDIS_URL=redis://redis:6379
      - EZAUTH_URL=${EZAUTH_URL}
    networks:
      - game-night-network

  match-creator:
    build:
      context: ./match-creator
    container_name: match-creator
    command: cargo run --release
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=${AMQP_URL}
    networks:
      - game-night-network

  games-agent:
    build:
      context: ./games-agent
    container_name: games-agent
    command: cargo run --release
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=${AMQP_URL}
    networks:
      - game-night-network

  automate:
    build:
      context: ./automate
    container_name: automate
    command: "python auto.py"
    restart: on-failure
    depends_on:
      - redis
    networks:
      - game-night-network
    environment:
      - SCRIPT_DIR=/usr/src/automate/scripts/matches.lua
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - game-night-network
    
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Password1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - game-night-network

networks:
  game-night-network:
    external: true
    driver: bridge