version: '3.8'

services:
  connector-api:
    build:
      context: ./connector-api
    image: cloudolife/col-rust-docker
    container_name: connector-api
    command: cargo run
    ports:
    - "4000:4000"
    restart: on-failure
    volumes:
      - "./connector-api:/usr/connector-api"
      - "./matchmaking-state:/usr/matchmaking-state"
    environment:
      - HOST_URL=0.0.0.0:4000

  monitoring_db:
    image: redis:latest
    container_name: monitoring_db
    ports:
      - "6379:6379"
    volumes:
      - monitoring_data:/data
    networks:
      - redis_network

volumes:
  monitoring_data:

networks:
  redis_network:
    driver: bridge