version: "3.8"

services:
  connector-api:
    build:
      context: ./connector-api
      args:
        - HOST_ADDR=0.0.0.0:4000
        - DEBUG=${DEBUG}
    container_name: connector-api
    command: connector-api
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - EZAUTH_URL=${EZAUTH_URL}
      - RANKING_URL=${RANKING_URL}
      - RANKING_API_KEY=${RANKING_API_KEY}
    networks:
      - game-night-network

  match-creator:
    build:
      context: ./match-creator
    container_name: match-creator
    command: match-creator
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=${AMQP_URL}
      - DEBUG=${DEBUG}
    networks:
      - game-night-network

  games-agent:
    build:
      context: ./games-agent
      args:
        - AMQP_URL=${AMQP_URL}
        - DEBUG=${DEBUG}
    container_name: games-agent
    command: games-agent
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=${AMQP_URL}
      - RANKING_URL=${RANKING_URL}
      - RANKING_API_KEY=${RANKING_API_KEY}
    networks:
      - game-night-network

  matchmaking-state-api:
    build:
      context: ./matchmaking-state-api
    container_name: matchmaking-state-api
    command: matchmaking-state-api
    restart: on-failure
    ports:
      - "6969:6969"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - HOST_URL=0.0.0.0:6969
      - EZAUTH_URL=${EZAUTH_URL}
      - DEBUG=${DEBUG}
    networks:
      - game-night-network

  automate:
    build:
      context: ./automate
    container_name: automate
    command: "python auto.py"
    restart: on-failure
    depends_on:
      - redis
    networks:
      - game-night-network
    environment:
      - SEARCHERS_SCRIPT_DIR=/usr/src/automate/scripts/searchers.lua
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=${DEBUG}

  redis:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: redis
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    networks:
      - game-night-network
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Password1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - game-night-network

networks:
  game-night-network:
    external: true
    driver: bridge
