version: "3.8"

services:
  connector-api:
    build:
      context: ./connector-api
      dockerfile: Dockerfile.dev
    container_name: connector-api
    command: cargo run
    ports:
      - "4000:4000"
    volumes:
      - ./matchmaking-state:/usr/matchmaking-state
      - "./matchmaking-state-types:/usr/matchmaking-state-types"
      - "./ezauth:/usr/ezauth"
    restart: on-failure
    depends_on:
      - redis
    environment:
      - HOST_ADDR=0.0.0.0:4000
      - REDIS_URL=redis://redis:6379
      - EZAUTH_URL=${EZAUTH_URL}
      - RANKING_URL=${RANKING_URL}
      - RANKING_API_KEY=${RANKING_API_KEY}
      - DEBUG=1
    networks:
      - game-night-network

  match-creator:
    build:
      context: ./match-creator
      dockerfile: Dockerfile.dev
    container_name: match-creator
    command: cargo run
    volumes:
      - ./matchmaking-state:/usr/matchmaking-state
      - "./matchmaking-state-types:/usr/matchmaking-state-types"
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=${AMQP_URL}
    networks:
      - game-night-network

  games-agent:
    build:
      context: ./games-agent
      dockerfile: Dockerfile.dev
    container_name: games-agent
    command: cargo run
    volumes:
      - ./matchmaking-state:/usr/matchmaking-state
      - ./matchmaking-state-types:/usr/matchmaking-state-types
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=${AMQP_URL}
      - RANKING_URL=${RANKING_URL}
      - RANKING_API_KEY=${RANKING_API_KEY}
      - DEBUG=1
    networks:
      - game-night-network

  matchmaking-state-api:
    build:
      context: ./matchmaking-state-api
      dockerfile: Dockerfile.dev
    container_name: matchmaking-state-api
    command: cargo run
    restart: on-failure
    ports:
      - "6969:6969"
    volumes:
      - "./matchmaking-state-types:/usr/matchmaking-state-types"
      - ./matchmaking-state:/usr/matchmaking-state
      - "./ezauth:/usr/ezauth"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - HOST_URL=0.0.0.0:6969
      - EZAUTH_URL=${EZAUTH_URL}
    networks:
      - game-night-network

  automate:
    build:
      context: ./automate
    container_name: automate
    command: "python auto.py"
    restart: on-failure
    depends_on:
      - redis
    networks:
      - game-night-network
    environment:
      - SEARCHERS_SCRIPT_DIR=/usr/src/automate/scripts/searchers.lua
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - game-night-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Password1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - game-night-network

networks:
  game-night-network:
    external: true
    driver: bridge
