[package]
name = "ezauth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
lazy_static = "1.5.0"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["json", "blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
